version: 2

defaults: &defaults
  docker:
    - image: golang:stretch
  working_directory: /workspace
  environment:
    GOPATH: /
    GOCACHE: /.cache/go-build
    GO111MODULE: "on"

jobs:
  setup-build:
    <<: *defaults
    steps:
      - run: go env
      - checkout
      - restore_cache:
          keys:
            - go-module-cache-v1-{{ checksum "/workspace/go.sum" }}
            - go-module-cache-v1-
      - run: go mod download
      - save_cache:
          key: go-module-cache-v1-{{ checksum "/workspace/go.sum" }}
          paths:
            - /pkg/mod/cache
      - save_cache:
          key: workspace-v1-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /workspace/

  test:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - workspace-v1-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - go-module-cache-v1-{{ checksum "/workspace/go.sum" }}
            - go-module-cache-v1-
      - restore_cache:
          keys:
            - go-build-cache-v1-{{ .Branch }}-{{ .Revision }}
            - go-build-cache-v1-{{ .Branch }}
            - go-build-cache-v1
      - run:
        name: "Create a temp directory for artifacts"
        command: |
          mkdir -p /tmp/artifacts
      - run:
          command: |
            go test -coverprofile c.out ./...
            go tool cover -html=c.out -o coverage.html
            mv coverage.html /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts            
      - save_cache:
          key: go-build-cache-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - /.cache/go-build

workflows:
  version: 2
  test:
    jobs:
      - setup-build
      - test:
          requires:
            - setup-build