name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test
      run: | 
       go test -coverprofile coverage.out ./...
       go tool cover -html=coverage.out -o coverage.html
    
    - name: Move
      run: |
        mkdir -p /tmp/artifacts
        mv coverage.out /tmp/artifacts
        mv coverage.html /tmp/artifacts

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        files: coverage.out, coverage.html
        directory: /tmp/artifacts
        fail_ci_if_error: true
        verbose: true
